services:
  # Servicio de base de datos PostgreSQL
  postgres:
    image: postgres:14
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  # Servicio de backend Node.js
  backend:
    build:
      context: ./backend
      dockerfile: ../backend.Dockerfile
    container_name: node_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: localhost
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - postgres
    networks:
      - app_network

  # Servicio de frontend React Native Expo
  frontend:
    build:
      context: ./frontend
      dockerfile: ../frontend.Dockerfile
    container_name: expo_frontend
    restart: always
    ports:
      - "19000:19000"  # Expo default port
      - "19001:19001"  # Metro bundler
      - "19002:19002"  # Expo Dev Tools
    environment:
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
      REACT_NATIVE_PACKAGER_HOSTNAME: ${REACT_NATIVE_PACKAGER_HOSTNAME}
      API_URL: http://backend:5000
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  node_modules:
  
